#Constants
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
GAME_LOOPS_PER_SECOND = 300
FRAMES_PER_PLAYER_MOVEMENT = 10
FRAMES_PER_PLAYER_BOLT_MOVEMENT = 1
PLAYER_MOVE_INCREMENTS = 10
PLAYER_FIRING_COOLDOWN = 100
PLAYER_BOLT_MOVE_INCREMENTS = 3
