# Constants for the game itself
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
GAME_LOOPS_PER_SECOND = 300
PLAYER_MOVE_INCREMENTS = 10
PLAYER_BOLT_MOVE_INCREMENTS = 3
ENEMY_DISTANCE_FROM_TOP = 40
ENEMY_DISTANCE_FROM_SIDE = 30
ENEMY_SPACE_BETWEEN = 10
